services:

  user-db:
    image: postgres:9-alpine
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - users-nw

  eureka-server:
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - services-nw

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - services-nw
      - users-nw
    depends_on:
      - eureka-server
      - user-db

volumes:
  user_data:

networks:
  users-nw:
    driver: bridge
  services-nw:
    driver: bridge